import { Document, Model, model, Schema } from 'mongoose';
import { Recipe } from './Recipe';

export interface IWeek extends Document {
    name: string,
    mondayB: Recipe,
    mondayL: Recipe,
    mondayD: Recipe,
    tuesdayB: Recipe,
    tuesdayL: Recipe,
    tuesdayD: Recipe,
    wednesdayB: Recipe,
    wednesdayL: Recipe,
    wednesdayD: Recipe,
    thursdayB: Recipe,
    thursdayL: Recipe,
    thursdayD: Recipe,
    fridayB: Recipe,
    fridayL: Recipe,
    fridayD: Recipe,
    saturdayB: Recipe,
    saturdayL: Recipe,
    saturdayD: Recipe,
    sundayB: Recipe,
    sundayL: Recipe,
    sundayD: Recipe,
}

const weekSchema: Schema = new Schema({
    name: {type: String, required: true},
    mondayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
        },
    mondayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    mondayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    tuesdayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    tuesdayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    tuesdayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    wednesdayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    wednesdayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    wednesdayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    thursdayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    thursdayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    thursdayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    fridayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    fridayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    fridayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    saturdayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    saturdayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    saturdayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    sundayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    sundayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    sundayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
});

const Week: Model<IWeek> = model('Week', weekSchema)

export default Week;