import { Document, Model, model, Schema } from 'mongoose';
import { IRecipe } from './Recipe';

export interface IWeek extends Document {
    name: string,
    mondayB: IRecipe[],
    mondayL: IRecipe[],
    mondayD: IRecipe[],
    tuesdayB: IRecipe[],
    tuesdayL: IRecipe[],
    tuesdayD: IRecipe[],
    wednesdayB: IRecipe[],
    wednesdayL: IRecipe[],
    wednesdayD: IRecipe[],
    thursdayB: IRecipe[],
    thursdayL: IRecipe[],
    thursdayD: IRecipe[],
    fridayB: IRecipe[],
    fridayL: IRecipe[],
    fridayD: IRecipe[],
    saturdayB: IRecipe[],
    saturdayL: IRecipe[],
    saturdayD: IRecipe[],
    sundayB: IRecipe[],
    sundayL: IRecipe[],
    sundayD: IRecipe[],
}

const weekSchema: Schema = new Schema({
    name: {type: String, required: true},
    mondayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
        },
    mondayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    mondayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    tuesdayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    tuesdayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    tuesdayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    wednesdayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    wednesdayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    wednesdayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    thursdayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    thursdayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    thursdayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    fridayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    fridayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    fridayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    saturdayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    saturdayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    saturdayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    sundayB: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    sundayL: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
    sundayD: {
        url: String,
        image: String,
        source: String,
        label: String,
        yield: Number,
        dietLabels: [String],
        healthLabels: [String],
        ingredientLines: [String],
        totalTime: Number,
        cuisineType: [String],
        mealType: [String],
        apiLink: String,
    },
});

const Week: Model<IWeek> = model('Week', weekSchema)

export default Week;